// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:c5348ad1-cd39-4a98-a0f7-56ec39f7fc30",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_XT5c8jAIY",
    "aws_user_pools_web_client_id": "d0ijscdpsk43duo6jnt7pdonp",
    "oauth": {
        "domain": "amplify-auth-abcedf-local.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://master.d3h5j4begww46c.amplifyapp.com/",
        "redirectSignOut": "https://master.d3h5j4begww46c.amplifyapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
